sudo: false
language: node_js
node_js:
- 6
- 8
notifications:
  email: false
  pushover:
    on_success: always
    on_failure: always
    template: |-
      %{repository_name} %{branch}#%{build_number}
      %{message}
      Details: %{build_url}
    api_key:
      secure: jrVaQ1ltiOVGgqAfp58PrU303oM7RZ/ghboTzrgrSbm7qz+Y8vkqnkR8BsDOfq483ShBiVRmLWUYZDUme/70jfIYUe+LKPLMqowB/KYoW3rBpCT2yMhvuddhqL0KK9qX+xFcyCWR5iHO61e1PJUKsR6UnsqueBRZT3GlvzsnLT5ajBoKCMnDDUC7HMKHHJ3nwMscsdj5ktCL6mvkOwDsBjD+7nNKF97xyVgCvFvhTjjimniBoIhbF2HZJooSJ/BVOzd0UAnDsJBpFNGPMalGBa8pS/FISf95MQJHOusP6vn9mipK3q3esep3MaEJZiwuYxggyD2c3BsV/OqB25hmeT+A/RgHl7NAdW2z6vB/3Vj3X8tZuwbyjzQlcLrLqp8AmIiZK084eBrENm+gi9TnT0TJBravwxE4j+fyQP/03AjwhLkRfgwylxxRxlHwCDX/H2lXgrlWe842jRsUGPhh+xeB6qyOadgtpMya3Lp59lLEXZYyOdPUSNeCXaqFxTB7DBdkaSR9jiwA2pPVn3EyKWKvc2LSAW8cWpLjYBG3se3QWZIGxni5P1Iw+ZfCwVde00NxxBomqeD9gnGInC90Jv8/9umfGLLvxYLXlSmjJqcPjZJsB8OCN4AnSfY7LGNVXZRxNKPIj6va6gVxMneURPEDa13pmeja1pTrO+bTQ9M=
    users:
      secure: V893OF2UQMFDng00CCTyLblrenuFCXtV4V3aOOjkfOgX4ln6zGwA9xLY19+r9MyvPLgFzwtG+vJdpPW1SBeSr1JdWsiyrYLZt34G5b/XQiOg/SDyF4QWbjPN3dw4jFJaZ9/qLQhUmPZpdAhSEYv4qICVuRIpDsiQdB08d9hBgFPC0spssd/9LP6YTaQ5Yngl/1i2yDo6IXsdX21ssAgPJ/dG+2PDl+8SwLEcPD8iIDBt3HxWY2ccqbKWSVZVoNWvSxLtwBPi3DXSy+uevyKUj6X0HAfTSH8g0rMct0eTjQRXzAHnI7nvBEk1wpkH2/gZ6u9WAGwAbpe6Id7iGmEe240iK7gHpamUj04NJ2n4+FHKIIgk4mLQuSH/P4Q5+h/Jz7GrkviECaEdiHEciZn5hPUni8TuL4BKaHw2YhTs492cUMun2S3jtM4p3OW0f+gYcLy9P8IzOuIJCKF0pF3vcrSaA41LIx/XTBSQNHnfLps94GUSUG3J+vTKcnnqeLggzuAeNqOxAhm5fBwKzI8W3Wepf9Hs4f73XjonoVmO5mk7Y4av1fqd5RtDg940kvgcKIIsdspdDPrtPbZE4WyT+0wGITiYxsFOFaCZQYn2rmxRnqZU5i8LK2bSaibkMeimTxQsrlbqMrd5NYqYlbbdtuTaxJh/TWAMhU3bqS+aNQo=
