sudo: false
language: node_js
node_js:
- 4
- 6
- 8
notifications:
  email: false
  pushover:
    on_success: always
    on_failure: always
    api_key:
      secure: oYMsfrGpfaBanr/IZ0yIqc4w0ZAxfWyWI+4bzLyJKBkqmWXsB9rFmAsb2wBYa/sVaOOQDtLJhlMdgT8EOhS67zx2I8DAULPdtZsJOFmxnb0LWXpCJraKsau5NjE9X8mvyDLLjK6p8UTeug5r9frHu50JWJsltGR3V4upPFJ0r5V7js88RkIf0h1AmXqKxsEhBE5++Y37nz9lJOSeDqcf38XVfHmph1yQGw7U6NMXQghxLvybYBOc0BZ4UIrqkviFoq+VuJ8ECPrEOR5zVRfgz4RLV2OxeDFY1b5wQ3F11gAQ5wiMh2uzzGXqxKyOcr2mnf2CiV2mITqVUXc645r4bary6F8NJLdYKO7VJ6ntxgBcGHFnrZJvkmuhohbx5f4NjL6BLrj9dhsPT5mrnrulG27tEn3NKk9ZoFEHdh5gEUxVD3/tN/xoqi2kO4Px6gwCoTNZSClSmhXJb+8lRAxPs2/37O5YZZU7s+Xdru8yHgoqgoP4mGI2CbIqGMBJ5W4t6iq16s5QT3iHOwSoywbEki/rI0Ca2XwHnMNx34gYkgAluvI4Bw1juYWZFHeUfzg2v7biaw4Lfz4YEPT5VhT1AcliWlpky2zm1AVsMY2HI/zXB0iQUwY0Evk6uvWvLdW7WK0xZA2Mvk07Qbt4T/as2EAGuLAkvV3NeXrO5JHvd+0=
    users:
      secure: IH3CkWb2uYd1FcIexFaucSrMVSuNMwxAWUJXXYyD716NBz9LTM3YXkoyVRfW5sCxpBPYOApszl1JGW4g6qIX+ka1yHmRlDL0LRJbfdz+pykT05jblF8uqnMitjarSkEnfZNdLbs0IXGCIy3RdY95EpehY6aZcLGfdaxLSJ3x75jLTAxeTwpN1e4tj9hQOQbRNL/ylJNCOTOfOmfEZRA/VFkNxHrdHxGHvSzW/QQCJNMrkBm1u4o3kkWean7MrjycuutAKT/m+45G0epIN+JdlS2YjAu2ohKFfgw1zL4/N+RMUas/48fjh6iVqFXJ3xfMxlACdiSEYn/jzlaowce+fMM0yqZGqAPXosHzdZI46JCm3efG1ttsqOvOqADFrGbisy5CBKQ6C1ugO9QAiFGSK7yEY02qQ6DhIhkLP0rMqzf34dW8di5O31FbM9Pf+nk8GkcRZ3Ol/Ya/k1tJZ0j+745BtaKPCRrk1YH7FmHeW7zrP8uyEI0/vFYRpM2ALWzk99hRDMHA6VB6CD6RngjNzCOcZoWiGjILvcHYh/Cf8yiEx26OwVwtFJSO10zU0jup0aPuihL9SOtuJYW61LLydG+7A3ukVD6QzlJyLdjcrsQ7RbvGwAn07DLCy17NOvugF22Wered/pLPEdNeEbLfwD0Gz78MYRaE6lYRWqEIjAs=
    template: |-
      %{repository_name} %{branch}#%{build_number}
      %{message}
      Details: %{build_url}
env:
  global:
    secure: GrbfFC9awjcdTLvtkJP4qhGMzICFOfBqWHt64Y0ysyzby5GKwNzYOjlMoCEvZA2PzBv70nU6RB7E046kp7DOpxnluu0PhHcHbeDRFszYiDd/S5Gt/Y6VxssgC5iu24ywLB9zbyEiGHL4GMKGr+mrbm34LgO4EsfYL7Tfk5/ozgDOy3ghlBNRsfRwpctU3xFEe1rVVBEvnAGQ/kBgqwuD3DdMGzh+wMSfogFI6pVqvVT9X8iSVQ6HJ07onX7CvTKBO19FpvZ+72DDFibpzMT4m8KBg76rhXuT2aJun9Ro4QiqILEpfSwLDeHyviX/zJ3D5EcTTofYoVCH/U38uc0Nq9mRl2hPtRzeTo7INKe6vAgz15Xg5qixoA5DVcQbiJsTsxqqV8XJNajdPirYT4QG1O0TnJYEbANbiZ5fo+JStLE0LZ1jFb4Dvg8xqmUj6XFiEEoV8WZMJ6X9pTfDJX3V7GyOa6JNz1LlthURherY7BrCDDgHRbuj46jzv6Mg9QkvHthekVTr4/MPBsTjT/dPoy0SkUJxLDMoFqNdW3vG66QoQEWKoMcwTJ+fWeknnNWz69YyRhNak6qYl1qMm4XfWpf5oYqeADTap3z7ZjVBj5AG0jmizbpQAyFRHCCJM5xAA3c/OlnYpnBU8/LnANU34j8t4hGshQPnWFw17WgDmk8=
